name:                hkhue
version:             0.1.0.0
github:              "prikhi/hkhue"
license:             BSD3
author:              "Pavan Rikhi"
maintainer:          "pavan.rikhi@gmail.com"
copyright:           "GPL-3.0"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/prikhi/hkhue#readme>

dependencies:
- base >= 4.7 && < 5
- text
- aeson
- data-default
- safe-exceptions
- websockets

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - containers
    - lens
    - lens-aeson
    - mtl
    - scientific
    - system-fileio
    - system-filepath
    - wreq
    - xdg-basedir
    - yaml

executables:
  hkhue:
    main:                Main.hs
    source-dirs:         cli
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hkhue
    - bytestring
    - cmdargs
    - network
    - tabular
    - typed-process

  hkhued:
    main:                Main.hs
    source-dirs:         daemon
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hkhue
    - containers
    - mtl
    - system-fileio
    - system-filepath
    - xdg-basedir
  wakeup:
    main:               Wakeup.hs
    source-dirs:        examples/wakeup
    dependencies:
    - hkhue
    - cmdargs
    - network
    - time
    - transformers

tests:
  hkhue-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hkhue
